version: "3.4"
services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - 8006:8006
    environment:
      MONGO_URI: mongodb://192.168.1.15:27017
      DATABASE: db
      COLLECTION: notes
      LOGIN_SERVICE_URL: http://192.168.1.15:30208
      CONTENT_SERVICE_URL: http://192.168.1.15:30677
